name: blind_help_new
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  audioplayers: ^6.0.0
  camera: ^0.10.0+3
  flutter_tts: ^3.2.0
  tflite_flutter: ^0.10.4
  image: ^3.0.1
  image_gallery_saver: ^2.0.3
  permission_handler: ^10.0.0
  http: ^0.13.3
  image_picker: ^0.8.4+7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0



flutter:
  uses-material-design: true
  assets:
    - assets/detected_braille_m.tflite
    - assets/alarm.mp3